(function(g){var window=this;var Yza=function(a,b){var c=[];g.$i(b,function(a){try{var b=g.JD.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ID(b)&&c.push(a):c.push(a)},a);
return c},Zza=function(a,b){var c=Yza(a,b);
(0,g.G)(c,function(a){g.JD.prototype.remove.call(this,a)},a)},$za=function(){var a=g.CH;
Zza(a,a.g.Yd(!0))},O7=function(a,b){g.O0.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.R=a;this.F={};this.P(a,"onMdxReceiversChange",this.I);this.P(a,"presentingplayerstatechange",this.I);this.I()},aAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},bAa=function(a,b){var c=new window.XMLHttpRequest;
c.onreadystatechange=function(){4==c.readyState&&200==c.status&&b(!0)};
c.onerror=function(){b(!1)};
try{c.open("GET",a,!0),c.send()}catch(d){b(!1)}},P7=function(){var a=aAa();
a&&a(!1,"No cast extension found")},Q7=function(a,b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},R7=function(a){if(a>=g.Jsa.length)P7();
else{var b=g.Jsa[a],c="chrome-extension://"+b+g.Gsa;0<=g.i2.indexOf(b)?bAa(c,function(d){d?(window.chrome.cast=window.chrome.cast||{},window.chrome.cast.extensionId=b,Q7(c,P7)):R7(a+1)}):Q7(c,function(){R7(a+1)})}},S7=function(a){return 0<=window.navigator.userAgent.indexOf(a)},cAa=function(){if(g.Hsa){var a=2,b=aAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Q7("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",P7,c)}},dAa=function(){if(S7("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){cAa();a({command:"cast.sender.init"});return}}if(!window.chrome||S7("Edge"))P7();else if(cAa(),S7("Android")&&S7("Chrome/")&&window.navigator.presentation){a="";var b=g.Nh();55<=b?a="55":50<=b&&(a="50");Q7("//www.gstatic.com/eureka/clank"+a+g.Gsa,P7)}else R7(0)},eAa=function(a){g.VG[a]&&(a=g.VG[a],(0,g.G)(a,function(a){g.TG[a]&&delete g.TG[a]}),a.length=0)},fAa=function(a){var b=g.SG();
if(b)if(b.clear(a),a)eAa(a);else for(var c in g.VG)eAa(c)},gAa=function(a){this.port=this.domain="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Fg(a)||"";b&&(this.port=":"+b);this.domain=g.Eg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Xa(a,"10.0")&&(this.o=!1))},hAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},iAa=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ya(a)},jAa=function(a,b){var c=g.Ad("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},kAa=function(){var a=iAa(),b=window.document.getElementById(a),c=b&&g.hG(b,"loaded");
c||b&&!c||(b=jAa(a,function(){g.hG(b,"loaded")||(g.gG(b,"loaded","true"),g.ZG(a),g.fF(g.Da(fAa,a),0))}))},lAa=function(){var a=0<=g.Hb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.WL||a},T7=function(a){g.SH("cloudview",a)},U7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},V7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},mAa=function(a,b,c,d){var e=!1;
V7()||(a=new g.TI(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.EH("yt-remote-cast-available",a);g.$G("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){T7("onReceiverSelected: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a);g.$G("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){T7("onReceiverResumed: "+a.friendlyName);
g.EH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){T7("onSessionChange: "+g.$H(a));
a||g.GH("yt-remote-cast-receiver");g.$G("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
T7("cloudview.createSingleton_: "+e);return e},nAa=function(a){T7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},oAa=function(){T7("dispose");
var a=V7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);nAa(!1);g.XG(W7);W7.length=0},X7=function(){return!!g.FH("yt-remote-cast-installed")},pAa=function(){var a=g.FH("yt-remote-cast-receiver");
return a?a.friendlyName:null},qAa=function(){T7("clearCurrentReceiver");
g.GH("yt-remote-cast-receiver")},Y7=function(a){g.SH("cloudview",a)},rAa=function(){return X7()?V7()?V7().getCastSession():(Y7("getCastSelector: Cast is not initialized."),null):(Y7("getCastSelector: Cast API is not installed!"),null)},Z7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},$7=function(){X7()?V7()?Z7()?(T7("Requesting cast selector."),V7().requestSession()):(T7("Wait for cast API to be ready to request the session."),W7.push(g.WG("yt-remote-cast2-api-ready",$7))):Y7("requestCastSelector: Cast is not initialized."):
Y7("requestCastSelector: Cast API is not installed!")},a8=function(a,b){Z7()?V7().setConnectedScreenStatus(a,b):Y7("setConnectedScreenStatus called before ready.")},b8=function(a){T7("setCastInstalled_ "+a);
g.EH("yt-remote-cast-installed",a)},sAa=function(a,b){V7().init(a,b)},tAa=function(a,b){b8(!0);
U7(!1);sAa(a,function(a){a?(nAa(!0),g.ZG("yt-remote-cast2-api-ready")):(Y7("Failed to initialize cast API."),b8(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),oAa());b(a)})},uAa=function(a,b,c,d,e,f,k){lAa()?mAa(b,e,f,k)&&(U7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?tAa(a,c):(window.__onGCastApiAvailable=function(b,d){b?tAa(a,c):(Y7("Failed to load cast API: "+d),b8(!1),U7(!1),g.GH("yt-remote-cast-available"),g.GH("yt-remote-cast-receiver"),oAa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):kAa():dAa())):T7("Cannot initialize because not running Chrome")},d8=function(a,b){g.JG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.XB;this.A=this.o=null;this.I=(0,g.z)(this.rO,this);this.F=(0,g.z)(this.ul,this);this.G=(0,g.z)(this.qO,this);this.J=(0,g.z)(this.EO,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mu,this),vAa(this))):c=3;0!=c&&(b?this.Mu(c):g.fF((0,g.z)(function(){this.Mu(c)},this),0));
var d=rAa();d&&c8(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},e8=function(a){return new g.ZI(a.B.getPlayerContextData())},vAa=function(a){(0,g.G)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.Da(this.IQ,a),this))},a)},wAa=function(a){(0,g.G)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},f8=function(a,b){50>a.C.Kc()&&g.ZB(a.C,b)},h8=function(a,b,c){var d=e8(a);
g.bJ(d,c);-1E3!=d.g&&(d.g=b);g8(a,d)},i8=function(a,b,c){a.B.sendMessage(b,c)},g8=function(a,b){wAa(a);
a.B.setPlayerContextData(g.eJ(b));vAa(a)},c8=function(a,b){a.A&&(a.A.removeUpdateListener(a.I),a.A.removeMediaListener(a.F),a.ul(null));
a.A=b;a.A&&(j8("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.I),a.A.addMediaListener(a.F),a.A.media.length&&a.ul(a.A.media[0]))},xAa=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=e8(a);b.contentId!=d.videoId&&j8("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.bJ(d,a.o.getEstimatedTime());g8(a,d)}else j8("No cast media video. Ignoring state update.")},j8=function(a){g.SH("CP",a)},k8=function(a,b,c){return(0,g.z)(function(a){this.bc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.bc("Retrying "+b+" using MDx browser channel."),i8(this,b,c))},a)},l8=function(a){g.eI.call(this,"ScreenServiceProxy");
this.cd=a;this.o=[];this.o.push(this.cd.$_s("screenChange",(0,g.z)(this.fU,this)));this.o.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.oQ,this)))},m8=function(){return g.x("yt.mdx.remote.currentScreenId_")},n8=function(a){g.SH("remote",a)},o8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},p8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},yAa=function(){var a=p8();
if(g.Xb(a)){a=g.kI();var b=g.FH("yt-remote-session-name")||"",c=g.FH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},zAa=function(a){a?(g.EH("yt-remote-session-app",a.app),g.EH("yt-remote-session-name",a.name)):(g.GH("yt-remote-session-app"),g.GH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},q8=function(){return g.x("yt.mdx.remote.connection_")},r8=function(){var a=q8();
return!!a&&3!=a.getProxyState()},AAa=function(){return g.x("yt.mdx.remote.connectData_")},t8=function(){if(!s8){var a=g.x("yt.mdx.remote.screenService_");
s8=a?new l8(a):null}return s8},u8=function(){var a=g.lI();
if(!a)return null;var b=t8().ge();return g.dI(b,a)},v8=function(){var a=m8();
if(!a)return null;var b=t8().ge();return g.dI(b,a)},BAa=function(){var a=t8().cd.$_gos();
var b=v8();b&&q8()&&(g.cI(a,b)||a.push(b));return hAa(a)},CAa=function(){var a=BAa(),b=v8();
b||(b=u8());return g.eb(a,function(a){return b&&g.XH(b,a.key)?!0:!1})},w8=function(){var a=CAa();
!a&&X7()&&pAa()&&(a={key:"cast-selector-receiver",name:pAa()});return a},DAa=function(){var a=BAa();
X7()&&g.FH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},EAa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},y8=function(a){var b=q8();
o8(null);a||EAa("");g.ua("yt.mdx.remote.connection_",a,void 0);x8&&((0,g.G)(x8,function(b){b(a)}),x8.length=0);
b&&!a?g.$G("yt-remote-connection-change",!1):!b&&a&&g.$G("yt-remote-connection-change",!0)},A8=function(a,b){v8()&&v8();
EAa(a.id);var c=new g.kJ(z8,a,p8());c.connect(b,AAa());c.subscribe("beforeDisconnect",function(a){g.$G("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){q8()&&y8(null)});
y8(c)},FAa=function(){var a=u8();
a?(n8("Resume connection to: "+g.$H(a)),A8(a,0)):(g.sI(),qAa(),n8("Skipping connecting because no session screen found."))},B8=function(){Z7()?V7().stopSession():Y7("stopSession called before API ready.");
var a=q8();a&&(a.disconnect(1),y8(null))},GAa=function(a){n8("remote.onCastSessionChange_: "+g.$H(a));
if(a){var b=v8();b&&b.id==a.id?a8(b.id,"YouTube TV"):(b&&B8(),A8(a,1))}else q8()&&B8()},HAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.yE("MDX_CONFIG")||b;g.CH&&$za();g.mI();z8||(z8=new gAa(b?b.loungeApiHost:void 0),g.uI()&&(z8.g="/api/loungedev"));x8||(x8=g.x("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",x8,void 0));yAa();var c=t8();if(!c){var d=new g.FI(z8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=t8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);uAa(a,d,function(a){a?m8()&&a8(m8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.$G("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),n8("Initializing: "+g.wg(b)),C8.push(g.WG("yt-remote-cast2-availability-change",function(){g.$G("yt-remote-receiver-availability-change")})),C8.push(g.WG("yt-remote-cast2-receiver-selected",function(){o8(null);
g.$G("yt-remote-auto-connect","cast-selector-receiver")})),C8.push(g.WG("yt-remote-cast2-receiver-resumed",function(){g.$G("yt-remote-receiver-resumed","cast-selector-receiver")})),C8.push(g.WG("yt-remote-cast2-session-change",GAa)),C8.push(g.WG("yt-remote-connection-change",function(a){a?a8(m8(),"YouTube TV"):u8()||(a8(null,null),qAa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.NF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),n8(" -- with channel params: "+
g.wg(a)),zAa(a),c.start(),m8()||FAa())},D8=function(a,b,c){g.L.call(this);
this.D=null!=c?(0,g.z)(a,c):a;this.uc=b;this.C=(0,g.z)(this.AH,this);this.g=!1;this.o=0;this.A=this.Aa=null;this.B=[]},E8=function(a,b,c){g.L.call(this);
this.F=a;this.R=b;this.o=new g.GG(this);g.M(this,this.o);this.o.P(b,"onCaptionsTrackListChanged",this.HP);this.o.P(b,"captionschanged",this.pO);this.o.P(b,"captionssettingschanged",this.JC);this.o.P(b,"videoplayerreset",this.Ao);this.o.P(b,"mdxautoplaycancel",this.IG);this.O=this.o.P(b,"onVolumeChange",this.cB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.pB,this);c.subscribe("remotePlayerChange",this.wl,this);c.subscribe("remoteQueueChange",this.Ao,this);c.subscribe("autoplayUpNext",this.OA,
this);c.subscribe("previousNextChange",this.mB,this);c.subscribe("nowAutoplaying",this.eB,this);c.subscribe("autoplayDismissed",this.NA,this);this.suggestion=null;this.G=new g.kR(64);this.A=new g.Mt(this.EC,500,this);g.M(this,this.A);this.B=new g.Mt(this.FC,1E3,this);g.M(this,this.B);this.J=new D8(this.CT,0,this);g.M(this,this.J);this.C={};this.L=new g.Mt(this.hD,1E3,this);g.M(this,this.L);this.I=new g.Ek(this.cL,1E3,this);g.M(this,this.I);this.N=g.y;this.JC();this.Ao();this.wl()},F8=function(a,b){var c=
a.F,d=a.R.ga().lengthSeconds;
c.I=b||0;c.g.U("progresssync",b,d)},IAa=function(a){F8(a,0);
a.A.stop();G8(a,new g.kR(64))},I8=function(a,b){if(H8(a)&&!a.D){var c=null;
b&&(c={style:a.R.pi()},g.dc(c,b));a.g.vC(a.R.ga(1).videoId,c);a.C=e8(a.g).o}},J8=function(a,b){var c=a.R.Tf();
if(c){var d=c.de();var e=c.listId.toString()}var f=a.R.ga(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.sj;var m=e8(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};g.dJ(m,k,l);g.t(b)&&(g.bJ(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);i8(c,"setPlaylist",q);e||g8(c,m);G8(a,new g.kR(1))},JAa=function(a,b){if(b){var c=a.R.zc("captions","tracklist",{zy:1});
c&&c.length?(a.R.Gd("captions","track",b),a.D=!1):(a.R.kl("captions"),a.D=!0)}else a.R.Gd("captions","track",{})},H8=function(a){return e8(a.g).videoId==a.R.ga(1).videoId},G8=function(a,b){a.B.stop();
var c=a.G;if(!g.qR(c,b)){var d=g.W(b,2);d!=g.W(a.G,2)&&g.RW(a.R,d);a.G=b;KAa(a.F,c,b)}},K8=function(a){g.Y.call(this,{H:"div",
M:"ytp-remote",K:[{H:"div",M:"ytp-remote-display-status",K:[{H:"div",M:"ytp-remote-display-status-icon",K:[g.DE()]},{H:"div",M:"ytp-remote-display-status-text",K:["{{statustext}}"]}]}]});this.o=new g.GX(this,250);g.M(this,this.o);this.A=a;this.P(a,"presentingplayerstatechange",this.B);LAa(this,g.OW(a))},LAa=function(a,b){if(3==a.A.Sa()){var c={RECEIVER_NAME:a.A.zc("remote","currentReceiver").name};
c=g.W(b,128)?g.U("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.W(b,4)?g.U("YTP_MDX_STATUS_PLAYING_2",c):g.U("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.o.show()}else a.o.hide()},L8=function(a){g.zX.call(this,a);
this.A={key:g.bI(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.kR(64);this.I=0;var b=g.HW(a).G;b&&(b=b.A&&b.A.g)&&(b=new O7(a,b),g.M(this,b));b=new K8(a);g.M(this,b);g.dX(a,b.element,4)},KAa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.vR(c,b))},M8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)B8();
else{a.B=b;var c=a.g.getPlaylistId();var d=a.g.ga(1),e=d.videoId;if(c||e){var f=a.g.Tf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.hc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.sj,index:Math.max(a.g.Hz(),0),currentTime:0==f?void 0:f}}else c=null;n8("Connecting to: "+g.wg(b));"cast-selector-receiver"==b.key?(o8(c||null),Z7()?V7().setLaunchParams(c||null):Y7("setLaunchParams called before ready.")):!c&&
r8()&&m8()==b.key?g.$G("yt-remote-connection-change",!0):(B8(),o8(c||null),c=t8().ge(),(c=g.dI(c,b.key))&&A8(c,1))}};
g.p(O7,g.O0);O7.prototype.I=function(){var a=this.R.zc("remote","receivers");a&&1<a.length&&!this.R.zc("remote","quickCast")?(this.F=g.Gb(a,this.B,this),g.P0(this,(0,g.H)(a,this.B)),a=this.R.zc("remote","currentReceiver"),this.mf(this.B(a)),this.enable(!0)):this.enable(!1)};
O7.prototype.B=function(a){return a.key};
O7.prototype.lf=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
O7.prototype.sd=function(a){g.O0.prototype.sd.call(this,a);this.R.Gd("remote","currentReceiver",this.F[a]);this.A.Ob()};
g.h=gAa.prototype;g.h.Zh=function(a){var b=this.g;if(g.t(void 0)?0:this.o)b="https://"+this.domain+this.port+this.g;return g.Og(b+a,{})};
g.h.Ku=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Gb:g.Da(this.aU,c,!0),onError:g.Da(this.ZT,d),td:g.Da(this.bU,d)};b&&(c.Pb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.vF(a,c)};
g.h.aU=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.ZT=function(a,b){a(Error("Request error: "+b.status))};
g.h.bU=function(a){a(Error("request timed out"))};
var W7=[];g.A(d8,g.JG);g.h=d8.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,k8(this,"play")):i8(this,"play"),h8(this,1,g.cJ(e8(this))),this.U("remotePlayerChange")):f8(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,k8(this,"pause")):i8(this,"pause"),h8(this,2,g.cJ(e8(this))),this.U("remotePlayerChange")):f8(this,this.pause)};
g.h.qD=function(a){if(1==this.g){if(this.o){var b=e8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,k8(this,"seekTo",{newTime:a}))}else i8(this,"seekTo",{newTime:a});h8(this,3,a);this.U("remotePlayerChange")}else f8(this,g.Da(this.qD,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,k8(this,"stopVideo")):i8(this,"stopVideo");var a=e8(this);a.index=-1;a.videoId="";g.$I(a);g8(this,a);this.U("remotePlayerChange")}else f8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=e8(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){j8("set receiver volume: "+d)},this),(0,g.z)(function(){this.bc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){j8("set receiver muted: "+b)},this),(0,g.z)(function(){this.bc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);i8(this,"setVolume",e)}c.muted=b;c.volume=a;g8(this,c)}else f8(this,g.Da(this.setVolume,a,b))};
g.h.vC=function(a,b){if(1==this.g){var c=e8(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.wg(b.style),g.dc(d,c.o));i8(this,"setSubtitlesTrack",d);g8(this,c)}else f8(this,g.Da(this.vC,a,b))};
g.h.Lu=function(a,b){if(1==this.g){i8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Rc.id});var c=e8(this);c.audioTrackId=b.Rc.id;g8(this,c)}else f8(this,g.Da(this.Lu,a,b))};
g.h.pD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);g.dJ(c,a,b);g8(this,c)}i8(this,"previous")}else f8(this,g.Da(this.pD,a,b))};
g.h.oD=function(a,b){if(1==this.g){if(a&&b){var c=e8(this);g.dJ(c,a,b);g8(this,c)}i8(this,"next")}else f8(this,g.Da(this.oD,a,b))};
g.h.Ow=function(){1==this.g?i8(this,"dismissAutoplay"):f8(this,this.Ow)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}d8.Z.dispose.call(this)};
g.h.X=function(){wAa(this);this.B=null;this.C.clear();c8(this,null);d8.Z.X.call(this)};
g.h.Mu=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.$B(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.IQ=function(a,b){this.U(a,b)};
g.h.rO=function(a){if(!a)this.ul(null),c8(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=e8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j8("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,g8(this,b)}};
g.h.ul=function(a){j8("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),xAa(this),this.U("remotePlayerChange")};
g.h.qO=function(a){a?(xAa(this),this.U("remotePlayerChange")):this.ul(null)};
g.h.EO=function(){var a=rAa();a&&c8(this,a)};
g.h.bc=function(a){g.SH("CP",a)};
g.A(l8,g.eI);g.h=l8.prototype;g.h.ge=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.kp=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.o.length;a<b;++a)this.cd.$_ubk(this.o[a]);this.o.length=0;this.cd=null;l8.Z.X.call(this)};
g.h.fU=function(){this.U("screenChange")};
g.h.oQ=function(){this.U("onlineScreenChange")};
var z8=null,x8=null,C8=[],s8=null;g.A(D8,g.L);g.h=D8.prototype;g.h.zH=function(a){this.B=arguments;this.g=!1;this.Aa?this.A=(0,g.F)()+this.uc:this.Aa=g.qg(this.C,this.uc)};
g.h.stop=function(){this.Aa&&(g.rg(this.Aa),this.Aa=null);this.A=null;this.g=!1;this.B=[]};
g.h.pause=function(){++this.o};
g.h.resume=function(){this.o&&(--this.o,!this.o&&this.g&&(this.g=!1,this.D.apply(null,this.B)))};
g.h.X=function(){this.stop();D8.Z.X.call(this)};
g.h.AH=function(){this.A?(this.Aa=g.qg(this.C,this.A-(0,g.F)()),this.A=null):(this.Aa=null,this.o?this.g=!0:(this.g=!1,this.D.apply(null,this.B)))};g.p(E8,g.L);g.h=E8.prototype;
g.h.X=function(){g.L.prototype.X.call(this);this.A.stop();this.B.stop();this.J.stop();this.N();this.g.unsubscribe("proxyStateChange",this.pB,this);this.g.unsubscribe("remotePlayerChange",this.wl,this);this.g.unsubscribe("remoteQueueChange",this.Ao,this);this.g.unsubscribe("autoplayUpNext",this.OA,this);this.g.unsubscribe("previousNextChange",this.mB,this);this.g.unsubscribe("nowAutoplaying",this.eB,this);this.g.unsubscribe("autoplayDismissed",this.NA,this);this.g=this.F=null};
g.h.yz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(H8(this)){if(1081!=e8(this.g).g||"control_seek"!=a)switch(a){case "control_toggle_play_pause":e8(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.gj(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Lu(this.R.ga(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.R.getCurrentTime();J8(this,0==c?void 0:c);break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":c=c[0],H8(this)&&this.g.Lu(this.R.ga(1).videoId,c)}};
g.h.pO=function(a){this.J.zH(a)};
g.h.CT=function(a){this.yz("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.JC=function(){var a=this.R.zc("captions","track");g.Xb(a)||I8(this,a)};
g.h.cB=function(a){if(H8(this)){this.g.unsubscribe("remotePlayerChange",this.wl,this);var b=Math.round(a.volume);a=!!a.muted;var c=e8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.L.start();this.g.subscribe("remotePlayerChange",this.wl,this)}};
g.h.HP=function(){g.Xb(this.C)||JAa(this,this.C);this.D=!1};
g.h.pB=function(a,b){this.B.stop();2==b&&this.FC()};
g.h.wl=function(){if(H8(this)){this.A.stop();var a=e8(this.g);switch(a.g){case 1081:case 1:G8(this,new g.kR(8));this.EC();break;case 1085:case 3:G8(this,new g.kR(9));break;case 1083:case 0:G8(this,new g.kR(2));this.I.stop();F8(this,this.R.ga().lengthSeconds);break;case 1084:G8(this,new g.kR(4));break;case 2:G8(this,new g.kR(4));F8(this,g.cJ(a));break;case -1:G8(this,new g.kR(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},G8(this,new g.kR(128,a))}a=e8(this.g).o;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,JAa(this,a));a=e8(this.g);-1==a.volume||Math.round(this.R.getVolume())==a.volume&&this.R.isMuted()==a.muted||this.L.isActive()||this.hD()}else IAa(this)};
g.h.mB=function(){this.R.U("mdxpreviousnextchange")};
g.h.Ao=function(){H8(this)||IAa(this)};
g.h.IG=function(){this.g.Ow()};
g.h.OA=function(a){a&&(a=g.vF("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Gb:(0,g.z)(this.JR,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.JR=function(a,b){var c=new g.lQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.R.U("mdxautoplayupnext",c)};
g.h.eB=function(a){(0,window.isNaN)(a)||this.R.U("mdxnowautoplaying",a)};
g.h.NA=function(){this.R.U("mdxautoplaycanceled")};
g.h.cL=function(a,b){-1==e8(this.g).g?J8(this,a):b&&this.g.qD(a)};
g.h.hD=function(){if(H8(this)){var a=e8(this.g);this.o.Ea(this.O);a.muted?this.R.mute():this.R.Uf();this.R.setVolume(a.volume);this.O=this.o.P(this.R,"onVolumeChange",this.cB)}};
g.h.EC=function(){this.A.stop();if(!this.g.ka()){var a=e8(this.g);a.kb()&&G8(this,new g.kR(8));F8(this,g.cJ(a));this.A.start()}};
g.h.FC=function(){this.B.stop();this.A.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(K8,g.Y);K8.prototype.B=function(a){LAa(this,a.state)};g.p(L8,g.zX);g.h=L8.prototype;g.h.create=function(){HAa(g.rO(g.X(this.g)));this.D.push(g.WG("yt-remote-before-disconnect",this.lO,this));this.D.push(g.WG("yt-remote-connection-change",this.SQ,this));this.D.push(g.WG("yt-remote-receiver-availability-change",this.nB,this));this.D.push(g.WG("yt-remote-auto-connect",this.QQ,this));this.D.push(g.WG("yt-remote-receiver-resumed",this.OQ,this));this.nB()};
g.h.load=function(){this.g.oq();g.zX.prototype.load.call(this);this.C=new E8(this,this.g,this.o);var a=(a=AAa())?a.currentTime:0;var b=r8()?new d8(q8(),void 0):null;0==a&&b&&(a=g.cJ(e8(b)));0!=a&&(this.I=a||0,this.g.U("progresssync",a,void 0));KAa(this,this.F,this.F);g.J1(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;g.zX.prototype.unload.call(this);g.J1(this.g.app,5)};
g.h.X=function(){g.XG(this.D);g.zX.prototype.X.call(this)};
g.h.al=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.yz.apply(this.C,[].concat([a],g.pa(c)))};
g.h.vH=function(){return this.loaded?this.C.suggestion:null};
g.h.Jf=function(){return this.o?e8(this.o).Jf:!1};
g.h.hasNext=function(){return this.o?e8(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.I};
g.h.FK=function(){var a=e8(this.o),b=this.g.ga();return{allowSeeking:this.g.dd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+g.aJ(a):a.B,isPeggedToLive:1>=(a.D?a.A+g.aJ(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+g.aJ(a):a.A,seekableStart:0<a.C?a.C+g.aJ(a):a.C}};
g.h.GK=function(){this.o&&this.o.oD()};
g.h.HK=function(){this.o&&this.o.pD()};
g.h.lO=function(a){1==a&&(this.J=this.o?e8(this.o):null)};
g.h.SQ=function(){var a=r8()?new d8(q8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.ga().videoId&&this.g.Fz(a.videoId,g.cJ(a)));this.g.U("videodatachange","newdata",this.g.ga(),3)};
g.h.nB=function(){this.G=[this.A].concat(DAa());var a=w8()||this.A;M8(this,a);this.g.va("onMdxReceiversChange")};
g.h.QQ=function(){var a=w8();M8(this,a)};
g.h.OQ=function(){this.B=w8()};
g.h.EK=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?$7():M8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&$7(),!0):!1}};
g.h.IK=function(){i8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.wd=function(){return!1};g.SZ.remote=L8;})(_yt_player);
